name: cicd
on: push
jobs:
    first:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-20, windows-latest]
        runs-on: ${{ matrix.os }}
        steps: 
            - name:
              run:
                echo "Hello World"  
                