name: cicd
on: push
jobs:
    first:
        runs-on: ubuntu-latest
        steps: 
            - name: docker setup
              uses: docker/setup-docker-actions@v4
            - name: echo docker details
              run: docker info
            - name: run image
              run: docker run hello-world
                